Repository TYPO3/Surf, pull requests merged in 2020-02, with the labels that each got.

#184 [TASK] Keep releases by Age
  Tests/Unit/Domain/Model/Clock/SystemClockTest.php
  Tests/Unit/Task/CleanupReleasesTaskTest.php
  src/Domain/Clock/ClockException.php
  src/Domain/Clock/ClockInterface.php
  src/Domain/Clock/SystemClock.php
  src/Task/CleanupReleasesTask.php
Labels: feature

#215 [FEATURE] Add scp transfer method
  Documentation/ApiReference/Task/Transfer/ScpTask.rst
  Documentation/ApiReference/Task/Transfer/index.rst
  Tests/Unit/Task/Transfer/ScpTaskTest.php
  src/Application/BaseApplication.php
  src/Task/Transfer/ScpTask.php
Labels: feature

#340 [BUGFIX] Set correct description for deploy command
  src/Command/DeployCommand.php
Labels: bug, easy pick

#339 [BUGFIX] Set scriptIdentifier for WebOpcacheResetExecuteTask in simulation
  src/Task/Php/WebOpcacheResetCreateScriptTask.php
Labels: bug

#338 [TASK] Beautify path concatenation
  src/Task/TYPO3/CMS/SymlinkDataTask.php
Labels: beautification
